CMakeLists.txt
eth/embobj/plus/comm-v2/icub/EoSkin.h
eth/embobj/plus/comm-v2/protocol/api/EoProtocolSK.h

increased eosk_capacity_arrayof_skincandata to 24, so that we can send regular ropframes less often

biggerskin

---

CMakeLists.txt
can/CMakeLists.txt
eth/CMakeLists.txt
icub_firmware_shared-config-version.cmake
icub_firmware_shared-config.cmake

This allows to set `icub_firmware_shared_DIR` to the source directory and therefore runing cmake and make is no longer required (unless you want the visual studio projects or similar).
I basically modified the generated files to add a regular expression to read the version from the `CMakeLists.txt` file.
Also restore installation that was removed in 0da92ea6ea3c922e82b51e7aa29acf514235ca15.
cc @traversaro

Allow using from source directory

---

eth/embobj/core/core/embOBJporting.h

This PR fixes the issue #25 Macro definition of snprintf conflicts with Standard Library function declaration
@traversaro

Include version check

---

CMakeLists.txt
eth/embobj/plus/comm-v2/icub/EoMotionControl.h
eth/embobj/plus/comm-v2/protocol/api/EoProtocolMC.h
eth/embobj/plus/comm-v2/protocol/src/EoProtocolMC_fun.c
eth/embobj/plus/comm-v2/protocol/src/EoProtocolMC_rom.c

This icub-firmware + icub-firmware-shared + icub-main package allows to configure the input of the 2FOC motor board (pwm, current, velocity) for each EMS control mode.

Flexible motor input on 2FOC boards

---

embot/prot/eth/embot_prot_eth.h
embot/prot/eth/embot_prot_eth_diagnostic.h
embot/prot/eth/embot_prot_eth_diagnostic_Host.cpp
embot/prot/eth/embot_prot_eth_diagnostic_Host.h
embot/prot/eth/embot_prot_eth_diagnostic_Node.cpp
embot/prot/eth/embot_prot_eth_diagnostic_Node.h
embot/prot/eth/embot_prot_eth_rop.cpp
embot/prot/eth/embot_prot_eth_rop.h
embot/prot/eth/embot_prot_eth_ropframe.cpp
embot/prot/eth/embot_prot_eth_ropframe.h
eth/embobj/core/core/EOpacket.c
eth/embobj/core/core/EOpacket.h
eth/embobj/plus/comm-v2/icub/EoError.c
eth/embobj/plus/comm-v2/icub/EoError.h

Added some embot objects which are required to be shared by both ETH boards and code running on icub-head (`icub-main` + `diagnostic-daemon`) 
Also, did small improvements to embobj's + and EoError.
They belong to namespaces `embot::prot::eth` + ` embot::prot::eth::diagnostic` and they:
- depend only from embot::core
- allow cross-platform generic handling of ETH protocol communication (rop, ropframe etc.)
- allow cross-platform handling of diagnostic messages equal to those defined by
{endpoint = management, entity = info, tag = eoprot_tag_mn_info_status}  and {endpoint = management, entity = info, tag = eoprot_tag_mn_info_status_basic}
Hence, they allow the use of a eth protocol tx/rx of diagnostic using an implementation much smaller and flexible than that inside the embobj library. …

embot::prot::eth

---

embot/core/embot_core.cpp
embot/core/embot_core.h

as per title. it is just a change in name.
the funtion `embot::core::delay()` was introduced in https://github.com/robotology/icub-firmware-shared/commit/ec83b8aab726672f8468d73789f859f2ebd464ad and was used only in `icub-firmware`, where is now substituted w/ `embot::core::wait()`.

embot::core::delay() renamed into embot::core::wait()

---

eth/embobj/plus/comm-v2/icub/EoError.c
eth/embobj/plus/comm-v2/icub/EoError.h

This PR adds some entries in the LUT of diagnostics errors which are related to not-supported services.
Pls see also https://github.com/robotology/icub-firmware/pull/144

Added extra diagnostics entries for disabled services

---

eth/embobj/core/core/EOaction.h
eth/embobj/plus/comm-v2/icub/EoAnalogSensors.c
eth/embobj/plus/comm-v2/icub/EoAnalogSensors.h
eth/embobj/plus/comm-v2/icub/EoError.c
eth/embobj/plus/comm-v2/icub/EoError.h
eth/embobj/plus/comm-v2/icub/EoManagement.c
eth/embobj/plus/comm-v2/icub/EoManagement.h
eth/embobj/plus/comm-v2/icub/EoMotionControl.c
eth/embobj/plus/comm-v2/icub/EoMotionControl.h
eth/embobj/plus/comm-v2/protocol/api/EoProtocol.h
eth/embobj/plus/comm-v2/protocol/api/EoProtocolAS.h
eth/embobj/plus/comm-v2/protocol/api/EoProtocolMN.h
eth/embobj/plus/comm-v2/protocol/src/EoProtocol.c
eth/embobj/plus/comm-v2/protocol/src/EoProtocolAS_fun.c
eth/embobj/plus/comm-v2/protocol/src/EoProtocolAS_rom.c

This PR introduces the `POS service`.
The POS service is used to stream position values from an `ETH` board towards the relevant device started by `yarprobotinterface`, the `embObjPOS`. The values are retrieved from up to 14 encoders, so far only magnetic encoders from the `pmc` board. The POS service is required to get position values of the fingers of the new hand. 
This PR is to be processed together with two other PRs: one for [`icub-firmware` ](https://github.com/robotology/icub-firmware/pull/147) and one for [`icub-main`](https://github.com/robotology/icub-main/pull/696).
In here are the main changes in each of these repositories. I describe them all together because one repo affects the other.
- `icub-firmware`:  added the `EOthePOS` object in ems, mc4plus, mc2plus; enabled in …

POS service

---

CMakeLists.txt

This is due to https://github.com/robotology/icub-firmware-shared/pull/42
It has to set as minimum required also in icub-main after https://github.com/robotology/icub-main/pull/696

Bump icub-firmware-shared version

---

eth/embobj/plus/comm-v2/icub/EoBoards.c
eth/embobj/plus/comm-v2/icub/EoBoards.h
eth/embobj/plus/comm-v2/icub/EoError.c
eth/embobj/plus/comm-v2/icub/EoError.h
eth/embobj/plus/comm-v2/icub/EoManagement.h
eth/embobj/plus/comm-v2/icub/EoMotionControl.c

This PR adds support for the MC service `eomn_serv_MC_mc4plusfaps` and for the required encoder's ports defined inside `eObrd_portpos_t`.
This PR is associated to [PR ](https://github.com/robotology/icub-firmware/pull/148) in `icub-firmware`.

Support for MC service of the new hand: open/close of fingers

---

eth/embobj/plus/comm-v2/transport/EOtransceiver.c
eth/embobj/plus/comm-v2/transport/EOtransmitter.c
eth/embobj/plus/comm-v2/transport/EOtransmitter.h

Added configurator for the remote address to work with eth boards with a different subnet than the standard 10.0.1.104
The software has been compiled also on the Linux machine running `yarprobotinterface` and it works.
Below an example of `yarprobotinterface` running with a gateway set to `10.0.2.104` connected to an `ems4` board with address `10.0.2.1` and an `F/T` sensor (`strain2`) connected to it
cc @marcoaccame @pattacini

ETH boards - added remote address configurator

---

CMakeLists.txt
eth/embobj/plus/comm-v2/icub/EoError.c
eth/embobj/plus/comm-v2/icub/EoError.h

This pull-request is a child of this other pull-request: [https://github.com/robotology/icub-firmware/pull/170](https://github.com/robotology/icub-firmware/pull/170).
It complements that pull-request to allow sending an info message when the encoder error disappears and the warning message counter is reset.
CC @marcoaccame @pattacini

Added info message for error reset

---

CMakeLists.txt
eth/embobj/plus/comm-v2/icub/EoManagement.c
eth/embobj/plus/comm-v2/icub/EoManagement.h
eth/embobj/plus/comm-v2/protocol/api/EoProtocolMN.h

This PR adds runtime configuration of additional diagnostics useful for debugging services on the robot. 
Runtime configuration means that yarprobotinterface collects some parameters from xml files and sends them to the ETH boards so that this one can use them to activate / tune some actions.
So far, only the AMO diagnostics in MC service is supported. 
See https://github.com/robotology/icub-firmware/pull/187

AMO diagnostics

---

CMakeLists.txt
eth/embobj/plus/comm-v2/icub/EoManagement.c
eth/embobj/plus/comm-v2/icub/EoManagement.h
eth/embobj/plus/comm-v2/icub/EoMotionControl.h
eth/embobj/plus/comm-v2/protocol/api/EoProtocolMC.h
eth/embobj/plus/comm-v2/protocol/api/EoProtocolMN.h
eth/embobj/plus/comm-v2/protocol/src/EoProtocolMC_fun.c
eth/embobj/plus/comm-v2/protocol/src/EoProtocolMC_rom.c

This PR belongs to a set of PRs which enable to stream AMO data towards YARP ports.
See robotology/icub-firmware#188 for details.
To enable the features of this PR we also need similar PRs. They are:
- in [`icub-firmware-shared`](https://github.com/robotology/icub-firmware-shared/pull/49) which contains the data structures,
-  in  [`icub-firmware`](https://github.com/robotology/icub-firmware/pull/188) we have the code for the ETH boards
- in [`icub-main`](https://github.com/robotology/icub-main/pull/753) which contains code to publish on the YARP port.
- in [`icub-firmware-build`](https://github.com/robotology/icub-firmware-build/pull/30) to give the new binaries for the `ems`, `mc4plus`, `mc2plus`.

AMO data to YARP ports

---

eth/embobj/plus/comm-v2/icub/EoMotionControl.c
eth/embobj/plus/comm-v2/icub/EoMotionControl.h

This PR adds the support for aea3 encoder.
In particular, it adds a new value `eomc_enc_aea3` in the enum type `eOmc_encoder_t` which is needed by these PRs on [`icub-firmware`](https://github.com/robotology/icub-firmware-shared/pull/50) and[ `icub-main`](https://github.com/robotology/icub-main/pull/769) to support the new sensors.
This change is backwards compatible with both repositories, so we can safely merge this PR before the other two.

add support for aea3 encoder

---

CMakeLists.txt
can/canProtocolLib/iCubCanProto_types.h
eth/embobj/plus/comm-v2/icub/EoBoards.c
eth/embobj/plus/comm-v2/icub/EoBoards.h

This PR allows the `FirmwareUpdater` in `icub-main` to recognize the board `amcbldc` for its operativity. 
In particular, with this [PR](https://github.com/robotology/icub-main/pull/778), the program `FirmwareUpdater` will be able to use the enum value dedicated to the `amcbldc`.
This change is small in size, but required also a change in the VERSION of icub_firmware_shared (from 1.22.0 to 1.22.1) in order to force icub-main to use it.

Basic support for board amcbldc

---

CMakeLists.txt
eth/embobj/plus/comm-v2/icub/EoMotionControl.h

This PR aims to complement the work done to address: https://github.com/robotology/community/discussions/561 , in which the feature request involved communicating the latest fault to the `yarpmotorgui`. To address it, the free space in the `motor_status_t` struct is filled with the error code associated to the most recent fault occurred on the joint, related to the category "motion controller". The data is retrieved by `embObjMotionControl` upon periodical request of the `yarpmotorgui`.
The fault states that can be communicated are the following:
```
{eoerror_value_MC_motor_external_fault,  "MC: exernal fault button pressed."},
{eoerror_value_MC_motor_overcurrent,     "MC: overcurrent. The motor has been turned off to prevent it from being damaged by an impulsive spike of current. par16 = …
```

Add latest fault state to motor status data structure

---

embot/core/embot_core.h

Sadly the previous [PR](https://github.com/robotology/icub-firmware-shared/pull/53) was not that backwards compatible so I am in here:
- adding back the method `std::uint8_t * getU08ptr() const` which is required by some `embot` object and 
- removing the  `Data(void *p, size_t s)` ctor which makes confusion w/ `constexpr Data(const void *p, size_t s)`.

Further changes to embot::core::Data 

---

CMakeLists.txt
eth/embobj/core/core/EoCommon.h
eth/embobj/plus/comm-v2/icub/EoAnalogSensors.c
eth/embobj/plus/comm-v2/icub/EoAnalogSensors.h
eth/embobj/plus/comm-v2/icub/EoBoards.c
eth/embobj/plus/comm-v2/icub/EoBoards.h
eth/embobj/plus/comm-v2/icub/EoError.c
eth/embobj/plus/comm-v2/icub/EoError.h
eth/embobj/plus/comm-v2/icub/EoManagement.c
eth/embobj/plus/comm-v2/icub/EoManagement.h
eth/embobj/plus/comm-v2/protocol/api/EoProtocol.h
eth/embobj/plus/comm-v2/protocol/api/EoProtocolAS.h
eth/embobj/plus/comm-v2/protocol/api/EoProtocolMN.h
eth/embobj/plus/comm-v2/protocol/src/EoProtocol.c
eth/embobj/plus/comm-v2/protocol/src/EoProtocolAS_fun.c
eth/embobj/plus/comm-v2/protocol/src/EoProtocolAS_rom.c

This PR with its companion PRs in [icub-firmware](https://github.com/robotology/icub-firmware/pull/257) and [icub-firmware-build](https://github.com/robotology/icub-firmware-build/pull/52) allow an ETH board such as the `ems`, `mc4plus`, `mc2plus` to stream FT data and associated temperature coming from one, two or more CAN FT sensor boards such as the `strain2` or the `strain`.
The changes generated by the above triad of PRs (`icub-firmware`, `icub-firmware-shared`, `icub-firmware-build`) can coexist safely with current release of `icub-main/devel`, even if the multiple FT service cannot be activated yet.
For further details see https://github.com/robotology/icub-firmware/pull/257.

FT service with multiple sensors

---

eth/embobj/plus/comm-v2/icub/EoBoards.c

This PR corrects a bug inside  `eoboards_string2reportmode()`  due to a typo which was  introduced in the previous [PR](https://github.com/robotology/icub-firmware-shared/pull/58).
The function `eoboards_string2reportmode()` will be used in `icub-main` to convert the string read from the xml files into valid `eObrd_canmonitor_reportmode_t` values for the future `embObjMultipleFTsensors` service.
Thanx @triccyx for having spotted the bug.

eoboards_string2reportmode() -> corrected bug due to typo

---

eth/embobj/plus/comm-v2/icub/EoBoards.c
eth/embobj/plus/comm-v2/icub/EoBoards.h

This PR contains the support for recognizing and printing the name of the `amc` board inside `FirmwareUpdater`.
It comes with a companion [PR](https://github.com/robotology/icub-firmware/pull/264), where we have added support in the `amc` board to talk to `FirmwareUpdater`.

ETH environment for the amc board

---

CMakeLists.txt
eth/embobj/plus/comm-v2/icub/EoMotionControl.h
eth/embobj/plus/comm-v2/protocol/api/EoProtocolMC.h

What chages this PR:
- Add a new `eOmc_kalman_filter_config_t` to `EoMotionControl` in order to allow the transfer of Kalman Filter configuration parameter between the `icub-main` and `icub-firnware`.
- Update `eOmc_joint_config_t`  and `eOmc_joint_t` structures to take account of the size of the new `eOmc_kalman_filter_config_t` structure
**Notes:**
None

Add eOmc_kalman_filter_config_t to EoMotionControl

---

CMakeLists.txt
can/canProtocolLib/iCubCanProto_types.h
eth/embobj/plus/comm-v2/icub/EoAnalogSensors.c
eth/embobj/plus/comm-v2/icub/EoAnalogSensors.h
eth/embobj/plus/comm-v2/icub/EoBoards.c
eth/embobj/plus/comm-v2/icub/EoBoards.h
eth/embobj/plus/comm-v2/icub/EoManagement.h
eth/embobj/plus/comm-v2/protocol/api/EoProtocolAS.h
eth/embobj/plus/comm-v2/protocol/api/EoProtocolMN.h

This PR adds support for the `mtb4c` boards and fixes the [eobrd_cantype_numberof](https://github.com/robotology/icub-firmware-shared/blob/bbb55d49051a6e9b7a39b77f70e372822089d40f/eth/embobj/plus/comm-v2/icub/EoBoards.h#L84) value.
cc @triccyx

Added mtb4c support

---

eth/embobj/plus/comm-v2/icub/EoBoards.c
eth/embobj/plus/comm-v2/icub/EoBoards.h

What changes this PR:
- Added new fields in `s_eoboards_map_of_connectors` in order to include the new J5 connector for AMC board.
**Notes:**
- Tested on `lego-setup`
- Be sure to use the proper configuration files in [`robots-configuration/experimentalSetups/lego_setup_amc_amcbldc`][1]
[1]: https://github.com/robotology/robots-configuration/tree/devel/experimentalSetups/lego_setup_amc_amcbldc

AMC – Add support for `J5_XY` connectors for AMC board

---

CMakeLists.txt
eth/embobj/plus/comm-v2/icub/EoBoards.h
eth/embobj/plus/comm-v2/icub/EoMotionControl.c
eth/embobj/plus/comm-v2/icub/EoMotionControl.h

What's new:
- Include `eomc_enc_aksim2` in `eOmc_encoder_t` to recognize the new AksIM2 from both `icub-main` and `icub-firmware`.
- Fix/Update the support for J5_XY connectors for `AMC` board
**Notes**
- none

EMS – Add support for AksIM2 encoder

---

eth/embobj/core/core/EOtimer.c
eth/embobj/core/core/EOtimer.h
eth/embobj/core/core/EOtimer_hid.h

Added dummy implementation of two functions for `EOtimer`:
- `eo_timer_SetName(EOtimer *t, const char *name)`
- `const char * eo_timer_GetName(EOtimer *t)`
I need the functions for a PR in `icub-firmware` so that I can track execution of multiple `EOtimer` objects but the functions are dummy, so they do not harm legacy code anywhere.

`EOtimer`: added dummy implementation of two functions

---

.github/workflows/ci.yml

Lately, macOS CI is failing because of `brew`.
Talking w/ @Nicogene, it came out that it would be nice to go w/ conda instead.
This PR removes macOS layers from the CI, in the meanwhile.

[CI] Remove macOS

---

CMakeLists.txt
eth/embobj/plus/comm-v2/icub/EoError.c
eth/embobj/plus/comm-v2/icub/EoError.h

**What's new:**
- the `eoerror_valuestrings_HW` list has been extended including possible error messages coming from the new `AksIM2` encoder.
- the `eOerror_value_HW_t` reflects the same changes
**Notes:**
- These changes are required to be able to parse the error messages sent from the new FW.
- Tested on `5-improved-joint` setup (composed by EMS + AksIM2 + BLDC Motor)
cc @ale-git @pattacini

Improved diagnostics for AksIM2 encoder extending existing data structures

---

CMakeLists.txt
eth/embobj/plus/comm-v2/icub/EoBoards.c
eth/embobj/plus/comm-v2/icub/EoBoards.h

This PR is linked to https://github.com/robotology/icub-firmware/pull/347 and allows the extension of the POS service to the boards `mtb4` and `mtb4c`.

FAP reading for `mtb4` and `mtb4c` 

---

CMakeLists.txt
eth/embobj/plus/comm-v2/icub/EoAnalogSensors.h
eth/embobj/plus/comm-v2/icub/EoBoards.c
eth/embobj/plus/comm-v2/icub/EoBoards.h

See robotology/robots-configuration#436
(unfortunately VS Code cleaned up the trailing space, I advice to review the changes ticking "[Hide whitespace](https://github.com/robotology/icub-firmware-shared/pull/78/files?w=1)")
TO BE TESTED

HandMK5: fix names of joints and connectors

---

CMakeLists.txt
eth/embobj/plus/comm-v2/icub/EoMotionControl.h

In this PR we added the data related to calibration 14: it is used for the open close joint f ergoCub fingers.
Even if the calibration 14 parameters hosts both motor encoder info and joint encoder (`FAP`)info,  currently only the data regarding the motor encoder are used: `pwmlimit` and `final_pos.` 
----------------
- [fw PR](https://github.com/robotology/icub-firmware/pull/363)
- [icub-main PR](https://github.com/robotology/icub-main/pull/862)
cc @MSECode

Added calibration 14 data struct

---

CMakeLists.txt
eth/embobj/plus/comm-v2/icub/EoMotionControl.c
eth/embobj/plus/comm-v2/icub/EoMotionControl.h

In this PR I added the `mrie` encoder type.
I updated the version to 1.34.2.
Even if this change doesn't affect the firmware, I'm going to compile all FWs and open a PR.
This PR is related with this [one](https://github.com/robotology/icub-main/pull/869) of icub-main.

Added the `mrie` encoder. Increase version to ` 1.34.2`

---

CMakeLists.txt
eth/embobj/core/core/EoCommon.h
eth/embobj/plus/comm-v2/icub/EoAnalogSensors.c
eth/embobj/plus/comm-v2/icub/EoMotionControl.c
eth/embobj/plus/comm-v2/icub/EoMotionControl.h

Update POS service and correlated methods for new calibration type 14 improvement
Specifically, important changes to check are the following:
- addition of the `typedef struct eOmap_int32_u08_t` used to map rotation values in `int32_t` with the ones in `uint8_t` used by the enum defined in the POS service
- definition of the `static array s_eomc_map_of_calib14rot` used for keeping the available values accepted for the rotation parameter
- definition of the method `eomc_int2calib14_ROT` used for performing the conversion from int32_t and uint8_t specific data type and inverse method `eomc_calib14_ROT2int` to convert a value of type `eOmc_calib14_ROT_t` to `int32_t`
- fix values of struct `eOmc_calibrator_params_type14_qenc_hard_stop_and_fap_t` by setting data type `int32_t` for rotation …

Calibration type 14 update and refactoring

---

CMakeLists.txt
eth/embobj/plus/comm-v2/icub/EoError.c
eth/embobj/plus/comm-v2/icub/EoError.h
eth/embobj/plus/comm-v2/icub/EoManagement.c
eth/embobj/plus/comm-v2/icub/EoManagement.h

Related to the https://github.com/robotology/icub-main/pull/886 PR, we updated the table containing the diagnostic message: we removed the part of the message that explained how to interpret the parameters because now it is performed automatically by the new formatter.
cc @MSECode

Updated the Table of diagnostic messages

---

CMakeLists.txt
eth/embobj/plus/comm-v2/icub/EoMotionControl.c
eth/embobj/plus/comm-v2/icub/EoMotionControl.h

Here I added only one type of constraint the the jointset configuration.
This PR is useful for https://github.com/robotology/icub-firmware/pull/424

Add ergocubwrist constraint in the joint mechanical specification 

---

CMakeLists.txt
eth/embobj/plus/comm-v2/icub/EoMotionControl.h
eth/embobj/plus/comm-v2/protocol/api/EoProtocolMC.h

**What's new:**
- the `eOmc_motor_params_t` structure has been extended with the new `velocityThres`
~~- the `bemf_value` and `bemf_scale` params have been removed from the `eOmc_motor_params_t` as they will not be used~~
> **Note**
> - tested on a single joint setup

Update EoMotionControl to support the new velocityThres parameter

---

eth/embobj/plus/comm-v2/icub/EoAnalogSensors.h

This PR is related to:
https://github.com/robotology/icub-firmware/pull/447

Add new eOas_batterymode_t enum for CAN TX modes

---

CMakeLists.txt
eth/embobj/plus/comm-v2/icub/EoManagement.c

Update:
- fix map array for service category
- Now the correct service category is printed in YRI

Fix s_mn_servicecategory_strings array

---

eth/embobj/plus/comm-v2/icub/EoMotionControl.h

Move MotorFaultState to EoMotionControl in order that we can use same type on both fw and sw.
Then add the enum typedef as guard
Change type mc_fault_state for being compliant with all definitions done in fw and sw
Related to: 
https://github.com/robotology/icub-firmware/pull/472
https://github.com/robotology/icub-main/pull/942

Move MotorFaultState to EoMotionControl

---

CMakeLists.txt
eth/embobj/plus/comm-v2/icub/EoAnalogSensors.h
eth/embobj/plus/comm-v2/protocol/api/EoProtocolAS.h

Changes of this PR:
- Reset status variable in struct `eOas_battery_timedvalue_t` datatype to uint16_t
- Correct the enum values and max dimension enum definitions of eOas_battery_alarm_status_t
- Update version to 1.38.2
Related to: 
- https://github.com/robotology/icub-firmware/pull/487
- https://github.com/robotology/icub-main/pull/953
- https://github.com/robotology/icub-firmware-build/pull/146

Update CMakeLists.txt with icub_firmware_shared version to 1.38.2

---

embot/CMakeLists.txt

https://github.com/robotology/icub-firmware-shared/pull/97 added a nested namespace (https://en.cppreference.com/w/cpp/language/namespace) to embot headers, that is a feature available only in C++17 . Recent versions of gcc and clang default to use C++17 so this is not a problem, while trying to compile the file in Visual Studio results in an error:
~~~
2024-10-01T03:15:18.9723412Z D:\a\robotology-superbuild\robotology-superbuild\src\icub_firmware_shared\embot\core\embot_core_binary.h(288,11): error C2429: language feature 'nested-namespace-definition' requires compiler flag '/std:c++17' [D:\a\robotology-superbuild\robotology-superbuild\b\src\icub_firmware_shared\embot\embot.vcxproj] [D:\a\robotology-superbuild\robotology-superbuild\b\icub_firmware_shared.vcxproj]
~~~
see …

Bump C++ version used in embot to C++17

---

can/canProtocolLib/iCubCanProto_types.h
eth/embobj/plus/comm-v2/icub/EoSkin.h

This PR just adds some macros and values for the skin type of `ergoCub` hand discussed in this PR:
- https://github.com/robotology/icub-firmware/pull/530
It can be merged w/out any harm.

Realigned types for skin type ERGOHAND

---

eth/embobj/plus/comm-v2/icub/EoBoards.c

Added `amcfoc` parsing as board with two cores.

 `amcfoc` two cores parsing

---

eth/embobj/plus/comm-v2/icub/EoBoards.c
eth/embobj/plus/comm-v2/icub/EoBoards.h

Adding `amcfoc` connectors and ports and the board in the can mask.
Now the string  `J11` / `J12` in an xml file that asks to board `amcfoc` to run the MC service will be correctly parsed by `yarprobotinterface` and sent to the board as port 0 / 1 that is associated signals on the physical `J11` / `J12` connector.

`amcfoc` connectors and ports

---

CMakeLists.txt
eth/embobj/plus/comm-v2/icub/EoError.c
eth/embobj/plus/comm-v2/icub/EoError.h
eth/embobj/plus/comm-v2/icub/EoMotionControl.h

This PR brings the following change:
- Add new errors for specifying the diagnostic of the AMO encoder
- Prepare new error for the case in which the TDB is not reading (currently the error cannot be enable since it is never sent by the 2FOC fw but it will be done soon)
- Update version to v1.41.3

Update error messages for temperature and amo

---

README.md
eth/CMakeLists.txt
eth/embobj_wireshark.lua

To debug some strange behavior on the robot, I developed a basic version of a [Wireshark dissector](https://www.wireshark.org/docs/wsdg_html_chunked/ChapterDissection.html) to analyze dump of UDP data capture on the robot, for example via `tcpdump`.
The wireshark dissector was heavily developed using LLMs, so it is possible that there are some parts that are a bit hallucinated. However, I heavily modify the code that dissected the tags, as that was not originally working in the initially llm-generated one. 
To get an idea of what you can see with the dissector, see this screenshot:
Full documentation to use the dissector was added in the README, so feel free to check it out.

Add initial version of embobj wireshark dissector

---

CMakeLists.txt
embot/tools/embot_tools.h
eth/embobj/plus/comm-v2/icub/EoError.c
eth/embobj/plus/comm-v2/icub/EoError.h
eth/embobj/plus/comm-v2/icub/EoManagement.h
eth/embobj/plus/comm-v2/protocol/api/EoProtocolMN.h

This PR adds support for the best effort mode for the execution of the RX, Do and TX phases for all ETH boards and for an improved reporting about their execution times.
In particular:
- improved `eOmn_appl_config_t` so that it contains extra parameters
- added new error codes for reporting overflows and statistics
Full details are in:
- https://github.com/robotology/icub-firmware/pull/617 for the new mode and for explanation of improved reporting,
- https://github.com/robotology/robots-configuration/pull/746 for how to use xml to configure the behavior of the ETH board
- https://github.com/robotology/icub-firmware/pull/617
- https://github.com/robotology/icub-firmware-shared/pull/115
- https://github.com/robotology/icub-main/pull/1030
- …

Best effort execution mode for RX, DO and TX phases of ETH boards

---

CMakeLists.txt
eth/embobj/plus/comm-v2/icub/EoMotionControl.h

The Kbemf (back EMF constant) has been added in EMS->2FOC motor configuration protocol.

2foc kbemf added in hardware/mechanicals 
